#!/bin/sh

# $Id: backup-rmgztk_morwen,v 1.6 2002-09-15 14:41:05 turbo Exp $

DATE=`date +"%Y%m%d"`
BACKUPDIR=/var/.backups && mkdir $BACKUPDIR/$DATE

BACKUPDIR=$BACKUPDIR/$DATE
BACKUPFILE1=$BACKUPDIR/confs-$DATE.tar.bz2
BACKUPFILE2=$BACKUPDIR/slapd-$DATE.ldif.bz2
BACKUPFILE3=$BACKUPDIR/krb5-$DATE
BACKUPFILE5=/etc/dpkg/selections-$DATE
BACKUPFILE7=$BACKUPDIR/oldlogs-$DATE.tar.bz2

BACKUPFILES="$BACKUPFILE1 $BACKUPFILE2 $BACKUPFILE3.bz2 $BACKUPFILE7"

BIGBACKUP=backups-`hostname`-$DATE.tar

cd /

# ----- L D A P -----
if [ -f /etc/init.d/slapd.backup ]; then
    /etc/init.d/slapd.backup stop > /dev/null 2>&1
    slapcat -n /var/lib/ldap.backup/id2entry.dbb | \
	egrep -v '^replace:' | \
	bzip2 > $BACKUPFILE2
    /etc/init.d/slapd.backup start > /dev/null 2>&1
fi

# ----- K E R B E R O S -----
kdb5_util dump $BACKUPFILE3
if [ -f $BACKUPFILE3.dump_ok ]; then
    bzip2 -9 $BACKUPFILE3
    rm $BACKUPFILE3.dump_ok
else
    echo "Could not dump krb5 db to $BACKUPFILE3!"
fi

# ----- I M P O R T A N T   C O N F I G F I L E S -----
dpkg --get-selections | gzip -f9 > $BACKUPFILE5
tar cjpsf $BACKUPFILE1 `find etc/ldap etc/krb5* \
    etc/pam.d var/lib/named/etc/bind etc/hosts* \
    etc/qmail etc/tcp.smtp etc/cron* etc/apache \
    etc/{nsswitch,danted,firewall.block,firewall}.conf \
    etc/init.d/{qmail,slapd,slapd.backup} \
    etc/profile etc/xinetd.d $BACKUPFILE5 \
	-type f | egrep -v '~$' | \
	sed -e 's@^/@@' -e 's@\.dpkg-dist@@' | \
	sort` 2> /dev/null

# -----------------
# Logfiles...
cd /var/log && tar --remove-files -cjf $BACKUPFILE7 `find -name '*.gz'`

# -----------------
# Archive all the backups into ONE file
cd $BACKUPDIR && tar --remove-files -cf ../$BIGBACKUP . \
    && cd .. && rm -Rf $BACKUPDIR && chmod 600 $BIGBACKUP

# Upload the backupfile to papadoc.
kinit -l 4m -k -t /etc/krb5.keytab.backup backup@BAYOUR.COM
rcp -D 2106 -x $BIGBACKUP backup@papadoc.bayour.com:/var/.backups/
kdestroy

# Remove the backup directory and the big backup file
rm -f $BIGBACKUP
