#!/bin/sh

sensors | egrep ' Fan| Temp' ; echo

for dev in /dev/hd? /dev/sd?; do
    smartctl -d ata -a $dev 2>&1 | grep Temperature_Celsius | \
        while read line; do
            # 194 Temperature_Celsius     0x0022   048   054   000    Old_age   Always       -       48 (Lifetime Min/Max 0/23)
            # 194 Temperature_Celsius     0x0022   034   055   000    Old_age   Always       -       34 (0 23 0 0)
            set -- `echo "$line"`
            shift ; shift ; shift ; shift ; shift ; shift ; shift ; shift ; shift

            set -- `echo "$*" | sed -e 's@/@ @' -e 's@(@@' -e 's@)@@'`
            tmp1=`echo "$1"`
            tmp2=`echo "$2"`
            tmp3=`echo "$3"`

            [ -z "$tmp2" -o "$tmp2" == "0" ] && tmp2="  "
            [ -z "$tmp3" -o "$tmp3" == "0" ] && tmp3="  "

            printf "$dev Temp:    +$tmp1°C  (low  =   %-2s°C, high =   %-2s°C)\n" "+$tmp2" "+$tmp3"
        done
done
